### ISSUE TITLE
Erreur dans le nombre d'items et la pagination dans l'administration

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#11]
Sur les pages de listes des paniers abandonnés dans l'administration, le nombre d'enregistrements affichés n'est pas le bon. Cela entraîne un dysfonctionnement de la pagination.

Exemple :
- j'ai un panier en attente avec 5 articles
- cela affiche bien une seule ligne dans le tableau des paniers
- mais cela affiche 5 enregistrements dans le nombre d'items

Ce comportement vient du fait que getCollection() et getSalesCollection() dans [Collection.php](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Collection.php) renvoient une ligne par article (et pas une ligne par panier).

**Comment by septoctobre** [comment]
Je pense qu'il faut surcharger getSelectCountSql() pour requêter le nombre de paniers en attente et retourner le nombre correct d'enregistrements. J'essaierai de travailler là-dessus à l'occasion.

**Comment by septoctobre** [comment]
Je finalise des tests et j'envoie un PR

**Comment by digitalpianism** [comment]
@septoctobre pareil dans ce cas j'ai pas utilisé la totalité de votre PR. J'essaye d'éviter au maximum de rewrite des classes de Magento pour assurer de ne rien casser. C'est un bug de Magento connu mais le but de ce module n'est pas de corriger les bugs de Magento. Du coup j'ai créé une collection que j'utilise directement dans Collection.php plutot que de continuer à utiliser catalog/product_collection

**Comment by septoctobre** [comment]
Ok c'est noté.

Pour ma compréhension : on évite les rewrite de classe sinon le nouvel objet surchargé est utilisé partout dans Magento (ce qui implique des risques en cas de mise à jour) alors qu'en procédant comme vous l'avez fait, l'objet surchargé n'est utilisé qu'au niveau du module. Mon raisonnement est correct ?

**Comment by digitalpianism** [comment]
@septoctobre c'est exactement ca ;)

**Comment by septoctobre** [comment]
@digitalpianism Ok, merci !
