### ISSUE TITLE
Format de la colonne "Total panier" dans l'admin

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#13]
Il y a quelques petites erreurs dans la liste des paniers abandonnés dans l'admin au niveau de la colonne "total panier" :
- absence de la devise
- alignement incorrect
- erreur de calcul/format du prix

**Comment by septoctobre** [comment]
En ce qui concerne l'erreur du calcul du "total panier", le problème est que le prix calculé pour le moment est un total des prix unitaires de chaque produit.

**Comment by septoctobre** [comment]
Le bug de calcul du "total panier" ne concerne que les "paniers abandonnés" et pas les "paniers abandonnés en promotion"

**Comment by digitalpianism** [comment]
@septoctobre pouvez-vous créer trois issues différentes ? est-ce que votre PR fixe les trois problemes listés ci dessus ?

**Comment by septoctobre** [comment]
@digitalpianism Je n'ai pas encore fini mais je pense que le PR va corriger tous les problèmes listés ici. Dans ce cas-là, est-ce nécessaire de faire 3 issues/PR ?

**Comment by digitalpianism** [comment]
@septoctobre non dans le cas ou le PR corrige les trois problemes on peut laisser cela comme ca

**Comment by septoctobre** [comment]
@digitalpianism Ok, c'est noté. Je mettrai un message sur le PR pour préciser quand j'ai terminé.
