### ISSUE TITLE
Sélection des "paniers abandonnés en promotion" et flat catalog

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#15]
Lorsque le flat catalog produit est activé, la sélection des "paniers abandonnés en promotion" ne retourne aucun résultat

**Comment by septoctobre** [comment]
Les 2 requêtes SQL sont correctes et renvoient bien les mêmes résultats si elles sont exécutées directement dans la base de données.

**Comment by septoctobre** [comment]
C'est bon, je vais envoyer un PR

**Comment by digitalpianism** [comment]
@septoctobre une erreur bête en effet alors que dans la condition sans le flat la condition était bonne

**Comment by septoctobre** [comment]
Ça arrive :)
