### ISSUE TITLE
Sélection des paniers abandonnés pour envoi via tâche cron

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#17]
Lors de l'envoi des emails de relance des paniers abandonnés via la tâche cron, tous les paniers sont sélectionnés (y compris ceux n'ayant pas atteint le délai renseigné dans l'admin)

**Comment by septoctobre** [comment]
En chargeant les paniers via l'admin, la requête se forme correctement en utilisant le délai renseigné dans l'admin. Le tri se fait avec quote_table.updated_at < "2016-11-14 08:55:29" (délai renseigné : un jour).

En lançant le traitement via la tâche cron, le tri se fait avec quote_table.updated_at < "2016-11-22 10:00:59".

**Comment by septoctobre** [comment]
Cela vient de [Notifier.php](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L565)

A mon avis, c'est if (!$delay) et non pas if (!$nodate).
Je vais tester ça et faire un PR.

**Comment by digitalpianism** [comment]
@septoctobre pas sur de bien comprendre celui la. `$nodate` c'est un résidu de l'ancienne version lorsqu'on voulait tester l'envoi à tout le monde peu importe le delai.

Mais il est désormais automatiquement à false dans la déclaration de la fonction.

Du coup cette condition ne doit jamais passer dans le else:

```
if (!$nodate) {
                    // Get the delay provided and convert it to a proper date
                    $delay = Mage::getStoreConfig('abandonedcartsconfig/options/notify_delay');
                    $delay = date('Y-m-d H:i:s', time() - $delay * 24 * 3600);
                }  else {
                    // We create a date in the future to handle all abandoned carts
                    $delay = date('Y-m-d H:i:s', strtotime("+7 day"));
                }
```

Normalement il n'y a pas de bugs de ce côté la

**Comment by septoctobre** [comment]
@digitalpianism 

Si le traitement est déclenché via l'admin, $nodate est bien null.

Mais en cas de traitement via tâche cron, $nodate n'est pas null, c'est un objet de type "cron object manager" (de mémoire, pas sûr pour le type exact).

**Comment by digitalpianism** [comment]
@septoctobre j'étais pas du tout au courant de ce fonctionnement de Magento. J'ai fais un fix qui est plus clair. Même si `$nodate` n'est plus utilisé il m'arrive pour certains tests de le réutiliser.

**Comment by septoctobre** [comment]
@digitalpianism Oui j'ai vu passer sur StackExchange Magento, je vais intégrer ça tout de suite !

**Comment by digitalpianism** [comment]
@septoctobre oui du coup j'ai réécri la signature des fonctions. J'aurais préféré un flag dans la config pour désactiver le premier parametre mais pas possible apparamment
