### ISSUE TITLE
Génération des images produit dans l'email

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#19]
Lors d'un envoi d'email de relance, si le visuel produit n'a encore jamais été généré pour les dimensions demandées, c'est le placeholder de base/default qui est renvoyé.

Lors d'un second envoi d'email de relance, le visuel produit ayant déjà généré pour les dimensions demandées, le visuel produit est correctement renvoyé.

(a priori, c'est le dernier bug que j'ai à faire remonter)

**Comment by septoctobre** [comment]
En fait, le bug n'intervient pas pour la première génération d'images (erreur de ma part).
Il se produit uniquement lorsque l'envoi est déclenché via tâche cron.
Je cherche encore la logique.

**Comment by septoctobre** [comment]
Ce bug ne se produit que sur mon serveur de production (tout est OK sur mon serveur de test).
Je me demande s'il ne s'agit pas d'un problème de configuration sur le serveur.

Pour un même produit :
- envoi manuel, $productImg renvoie l'image attendue
- envoi via cron, $productImg renvoie le placeholder

**Comment by septoctobre** [comment]
Finalement, ce bug ne venait pas de DigitalPianism_Abandonedcarts puisque j'avais le même problème avec les alertes de disponibilité produits.

Pour info, cela venait de la définition de memory_limit pour PHP-CLI.

**Comment by digitalpianism** [comment]
@septoctobre haha cette bonne vieille memory_limit qui fait des siennes
