### ISSUE TITLE
Génération des tokens de connexion

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#20]
La génération des tokens avec des caractères exotiques via openssl_random_pseudo_bytes() semble empêcher l'ouverture du lien de récupération du panier avec la plupart des clients mail.

Je pense qu'il vaut mieux utiliser Mage::helper('core')->uniqHash() pour éviter ce problème et rester cohérent avec l'existant de Magento.

**Comment by digitalpianism** [comment]
@septoctobre j'ai merge la PR je serais curieux de savoir quel problème avez vous rencontré exactement avec openssl_random_pseudo_bytes ?

**Comment by septoctobre** [comment]
@digitalpianism 
L'URL formée avec le token généré via openssl_random_pseudo_bytes() (&token=%AAB%5D%D8%B1%F3%CA5%2C) a l'air de poser des problèmes d'interprétation à certains clients mail. Il en résultait un lien inactif (le lien était cliquable mais ne déclenchait pas l'ouverture de la page web).

**Comment by septoctobre** [comment]
Le token apparaissait sous cette forme &token=%AAB%5D%D8%B1%F3%CA5%2C
