### ISSUE TITLE
Date de création du panier altérée

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#23]
Lors de l'envoi des emails de relance (action manuelle ou cron), avec le mode test non activé, la date de création du panier est altérée (la date normale est remplacée par la date d'envoi du mail). 

Ce comportement semble venir d'[ici](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Sales/Resource/Quote.php#L13-L36) même si la requête d'UPDATE est propre.

**Comment by digitalpianism** [comment]
@septoctobre la date de création ? la date de mise à jour plutot non ?

**Comment by septoctobre** [comment]
@digitalpianism bizarrement, il s'agit bien de la date de création

**Comment by digitalpianism** [comment]
@septoctobre étrange, la date de création devrait s'initialiser à l'insertion et la date de mise à jour à l'update.

**Comment by septoctobre** [comment]
@digitalpianism tout à fait (c'est discutable mais je pense que l'envoi du mail ne devrait pas non plus altérer la date de modification)

**Comment by digitalpianism** [comment]
@septoctobre bug Magento: https://www.maximehuran.fr/corriger-le-bug-des-champs-created_at-et-updated_at/

La date de modification n'est pas importante dans le cas de la table sales_flat_quote. Ce n'est pas idéal en effet mais aucun impact sur Magento donc faute de mieux je laisse comme ça.

L'alternative serait de créer une nouvelle table ou l'on stockerait les quotes qui ont été notifiées. Mais ca rajouterait un join à la requête (qui est déjà assez longue) et en terme de performance j'suis pas sur que ce soit idéal.

**Comment by septoctobre** [comment]
@digitalpianism en effet, bien vu pour le bug, merci
Ce serait un peu de l'overkill de rajouter un traitement juste pour ça donc je clos ce ticket.

**Comment by digitalpianism** [comment]
@septoctobre je pense aussi. Merci à vous pour le retour en tout cas.
