### ISSUE TITLE
Translations need to be loaded

### ISSUE THREAD

**Issue by gstrat88** [digitalpianism/abandonedcarts#26]
Because of this:

https://magento.stackexchange.com/questions/25612/cron-job-template-block-not-being-translated-but-testobserver-is

I need to add this line of code after setArea in _sentEmails function:
```
//Dealing with uninitialized translator!
Mage::app()->getTranslator()->init('frontend', true);
```

**Comment by digitalpianism** [comment]
@gstrat88 thanks for this issue and sorry for the late reply. Could you tell me exactly where you wrote that piece of code or if possible, create a pull request please ?

**Comment by gstrat88** [comment]
Model/Notifier.php class DigitalPianism_Abandonedcarts_Model_Notifier function _sentEmails 

line 378
after Mage::getDesign()->setArea('frontend');
