### ISSUE TITLE
Sélection de l'image produit dans l'email de relance

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#3]
Bonjour,

Sauf erreur de ma part, je pense avoir détecté un petit problème dans la sélection de l'image produit affichée dans l'email de relance.

La méthode _getProductImage() dans app\code\community\DigitalPianism\Abandonedcarts\Model\Notifier.php me renvoie la "base image" au lieu de la "small image".

J'obtiens le comportement voulu en ajoutant l'attribut "small_image" à la sélection et en supprimant la jointure.

**Comment by digitalpianism** [comment]
@septoctobre bonjour et merci pour la remontée de bug. Il est possible qu'il y ait en effet un bug sur cette fonction. Pouvez-vous faire un PR avec votre code modifié que je puisse faire différent tests ?

**Comment by septoctobre** [comment]
Pas de problème, avec plaisir.
Dès que j'ai un peu de temps pour créer un environnement dédié à cette extension, je fais le PR.

**Comment by digitalpianism** [comment]
@septoctobre super merci à vous
