### ISSUE TITLE
Utilisation d'un gabarit d'email par défaut pour la langue

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#4]
Bonjour,

Je pense avoir détecté une erreur dans la gestion des gabarits.

Lorsque "Système > Configuration > Email Configuration > Gabarit d'email pour les paniers abandonnés [...]" est configuré sur "gabarit par défaut pour la langue", le template "\app\locale\fr_FR\template\email\digitalpianism\abandonedcarts\sales_abandonedcarts.html" devrait être utilisé (fonctionnement par défaut de Magento).

Or cela déclenche une erreur : "DigitalPianism_Abandonedcarts_Model_Notifier::sendAbandonedCartsEmail->Error: Invalid transactional email code: abandonedcartsconfig_email_email_template" et l'email ne part pas.

Aucun problème à signaler si un template spécifique a bien été créé dans "Système > Emails transactionnels" puis renseigné dans "Système > Configuration > Email Configuration > Gabarit d'email pour les paniers abandonnés [...]".

**Comment by digitalpianism** [comment]
@septoctobre en effet, il s'agit d'un bug, le correctif est assez simple j'essaye de sortir ca assez rapidement

**Comment by septoctobre** [comment]
J'ai aussi préparé un quickfix de mon côté si besoin

**Comment by digitalpianism** [comment]
@septoctobre c'est résolu ;)

**Comment by septoctobre** [comment]
c'est plus simple comme ça, merci !
