### ISSUE TITLE
Erreur dans la surcharge des templates

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#7]
Si je surcharge les templates présents dans "app\design\frontend\base\default\template\digitalpianism\abandonedcarts\email\" en les copiant dans "app\design\frontend\MYPACKAGE\default\template\digitalpianism\abandonedcarts\email\", ces derniers ne sont pas pris en compte.

**Comment by digitalpianism** [comment]
@septoctobre c'est pas un probleme generique à Magento ? ou il faut préciser le package et theme directement dans le body de l'email ?

**Comment by septoctobre** [comment]
Il me semblait que le comportement par défaut était d'abord d'aller chercher les fichiers dans MYPACKAGE\default puis dans base\default.

J'ai tenté d'inclure le block comme suit dans sales_abandonedcarts.html :

`{{block type='core/template' package='MYPACKAGE' area='frontend' template='digitalpianism/abandonedcarts/email/items.phtml'}}`

Mais le résultat est le même.

**Comment by digitalpianism** [comment]
@septoctobre il faut que je fasse des tests dès que j'aurais un peu de temps.

Je récapitule la procédure à suivre, merci de me confirmer:
- copy du template app/design/frontend/base/default/digitalpianism/abandonedcarts/email/items.phtml and app/design/frontend/package/theme/digitalpianism/abandonedcarts/email/items.phtml ou package/theme correspond à la configuration de la boutique.
- modification dans le template copié
- template copié non pris en compte lors de l'envoi de l'email à un client assigné à cette boutique (store)
- template copié non pris en compte avec spécification explicite du package et de l'area

**Comment by septoctobre** [comment]
C'est exactement ça.

2 petites précisions concernant les inclusions de block dans les emails transactionnels :
- je ne pense pas qu'il soit nécessaire de définir explicitement le package lorsqu'il correspond à celui défini dans la configuration de la boutique
- je ne suis pas sûr de la syntaxe que j'ai utilisée pour définir explicitement le package

**Comment by digitalpianism** [comment]
@septoctobre d'accord avec le point numéro 1. Pour le point numéro il me semble que c'est `_package`, `_theme` et `_area`

**Comment by septoctobre** [comment]
Après un nouvel essai, je confirme que cela ne fonctionne pas

**Comment by digitalpianism** [comment]
@septoctobre j'ai bien noté je me penche dessus dès que possible en attendant je ne peux que vous conseiller la modification direct des templates dans base/default . Pensez à faire une copie de vos templates modifiés pour éviter la perte des modifications lors que la MAJ du module

**Comment by septoctobre** [comment]
Pas de problème, ce n'est pas bloquant.
