### ISSUE TITLE
Erreur dans le chargement des css spécifiques aux emails transactionnels

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#8]
En voulant transformer l'email de relance pour utiliser la même structure que les autres emails transactionnels depuis la 1.9.1 (inclusion de header, footer, email-non-inline.css et email-inline.css), je me suis rendu compte que les fichiers CSS n'étaient pas chargés.

En creusant un peu, je note que les CSS sont chargés à partir de "skin/adminhtml/base/default/css/" au lieu de "skin/frontend/base/default/css/" (ou "skin/fontend/MYPACKAGE/default/css/").

Sans doute lié à l'issue #7 
Je pense à une erreur dans le fichier de config.

**Comment by digitalpianism** [comment]
@septoctobre normalement le store id est assigné ici: https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362

En général, l'affectation du store id est le point de départ de la selection des bons chemins de theme/skin. Par hasard, est-ce que le client que vous utilisez pour faire vos tests ne serait pas un client seulement assigné au store admin ?

**Comment by septoctobre** [comment]
Je pense que ma configuration est correcte concernant le client de test.
Le store id assigné dans [https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362) est le bon.

**Comment by digitalpianism** [comment]
@septoctobre pour tester vous utilisez la grille du backoffice ?

**Comment by septoctobre** [comment]
Pour l'assignation du client à la boutique : oui
Pour l'assignation du store id : debug dans [https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362)

Au niveau de cette erreur, je vois un problème via le fichier app\code\core\Mage\Core\Model\Email\Template\Abstract.php dans la méthode _getCssFileContent().

`$area = $this->getDesignConfig()->getArea();`

donne 'adminhtml' alors que 'frontend' est normalement attendu.

**Comment by digitalpianism** [comment]
@septoctobre je vois je pense qu'il faut que je précise l'area explicitement en même temps que le store id en me basant sur la valeur du store id (area = adminhtml si 0 sinon area = frontend)

**Comment by septoctobre** [comment]
J'essaie ça dès que j'ai trouvé quelle est la méthode à utiliser

**Comment by septoctobre** [comment]
Je peux confirmer qu'en ajoutant 
`Mage::getDesign()->setArea('frontend');`

après [https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362](https://github.com/digitalpianism/abandonedcarts/blob/master/app/code/community/DigitalPianism/Abandonedcarts/Model/Notifier.php#L362), on retrouve le comportement attendu.

**Comment by septoctobre** [comment]
Et je confirme que cela a aussi réparé l'issue #7  =)

**Comment by digitalpianism** [comment]
@septoctobre j'ai fais un commit vous pouvez essayer svp ?

**Comment by digitalpianism** [comment]
@septoctobre j'ai fais un second commit j'avais laissé du code mort.

**Comment by septoctobre** [comment]
J'avais effectué des modifications avant de faire un fork. Ce n'était clairement pas ma meilleure idée...

J'ai appliqué les modifs. Est-ce normal que je vois des lignes inutiles dans _sendEmails() ligne 381 à 383 ?

**Comment by digitalpianism** [comment]
@septoctobre j'avais laissé du code mort j'ai fais un second commit

**Comment by septoctobre** [comment]
Voici le résultat du test :
Fatal error: Call to undefined method Mage_Core_Model_App::getDesign()

Y a-t-il un problème à utiliser Mage::getDesign()->setArea('frontend'); ?

**Comment by digitalpianism** [comment]
@septoctobre je fais des tests de mon côté je vous tiens au courant

**Comment by septoctobre** [comment]
Ça marche, je vais utiliser mon quickfix en attendant

**Comment by digitalpianism** [comment]
@septoctobre stupide erreur. C'était Mage::getDesign() et non Mage::app()->getDesign() j'ai fais un nouveau commit avec un code que j'ai testé ca a l'air de fonctionner correctement, merci de me confirmer

**Comment by septoctobre** [comment]
Je me disais bien... ;)
Je teste ça !

**Comment by septoctobre** [comment]
C'est bon pour moi, les 2 issues sont résolus, merci !
