### ISSUE TITLE
Erreur quand on filtre les paniers abandonnés dans l'administration

### ISSUE THREAD

**Issue by septoctobre** [digitalpianism/abandonedcarts#9]
Sur la page d'administration, si je filtre les paniers abandonnés (par exemple par email ou par date), j'obtiens l'erreur suivante : 

Fatal error: Call to a member function toString() on a non-object in app/code/community/DigitalPianism/Abandonedcarts/Block/Adminhtml/Abandonedcarts/Grid.php on line 207

**Comment by digitalpianism** [comment]
@septoctobre j'ai modifié le code que vous aviez utilisé pour faire quelquechose de plus stable.

**Comment by septoctobre** [comment]
C'est noté, merci.
Si je fais une nouvelle PR, je penserai à fetch et rebase avant.
